#!/usr/bin/env escript

main([Filename]) ->
    Rel = erlang:system_info(otp_release),
    File = filename:join([code:root_dir(), "releases", Rel, "OTP_VERSION"]),
    case file:read_file(File) of
        {error, _} ->
            halt(1);
        {ok, Vsn} ->
            Vsn1 = io_lib:format("~s", [binary:replace(Vsn, <<"\n">>, <<>>)]),
            ok = file:write_file(Filename, Vsn1)
    end.

